name: Render and Deploy Report

on:
  schedule:
    - cron: '0 9 * * 1'  # Runs every Monday at 9 AM UTC '0 9 * * *' = Every day at 9 AM || '0 9 * * 1-5' = Every weekday at 9 AM || '0 0 1 * *' = First day of each month at midnight|| '0 */6 * * *' = Every 6 hours
  workflow_dispatch:  # Allows manual trigger
  push:
    branches: [main]

jobs:
  render-deploy:
    runs-on: ubuntu-latest # Sets up a virtual Ubuntu computer
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'
      
      - uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Install R packages
        run: |
          install.packages(c("ggplot2", "rmarkdown"))
        shell: Rscript {0}
      
      - name: Render Quarto Report
        run: quarto render report.qmd
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          publish_branch: gh-pages